/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#c8c8b0",
        "on-surface-variant": "#c8c7bc",
        "primary-fixed": "#e4e4cc",
        "surface-bright": "#3a3939",
        "on-tertiary-fixed-variant": "#3a4a41",
        "on-surface": "#e5e2e1",
        "tertiary-fixed-dim": "#b9cbbe",
        "tertiary-container": "#d5e7da",
        "inverse-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "on-secondary-fixed-variant": "#444655",
        "surface-tint": "#c8c8b0",
        "on-tertiary-container": "#58685e",
        "primary": "#ffffff",
        "on-secondary-fixed": "#191b29",
        "on-background": "#e5e2e1",
        "secondary": "#c5c5d8",
        "on-secondary-container": "#b6b7ca",
        "tertiary-fixed": "#d5e7da",
        "primary-container": "#e4e4cc",
        "error-container": "#93000a",
        "inverse-primary": "#5e604d",
        "surface-container-high": "#2a2a2a",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#0f1f16",
        "outline-variant": "#47473f",
        "background": "#131313",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#474836",
        "error": "#ffb4ab",
        "secondary-fixed": "#e1e1f5",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed": "#1b1d0e",
        "secondary-container": "#464858",
        "surface-variant": "#353534",
        "on-primary": "#303221",
        "surface-container": "#201f1f",
        "inverse-on-surface": "#313030",
        "secondary-fixed-dim": "#c5c5d8",
        "on-secondary": "#2e2f3e",
        "surface-container-highest": "#353534",
        "surface-container-low": "#1c1b1b",
        "surface": "#131313",
        "tertiary": "#ffffff",
        "on-tertiary": "#24342b",
        "on-primary-container": "#646652",
        "outline": "#929187",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        margin: "32px",
        xl: "40px",
        xs: "4px",
        sm: "8px",
        gutter: "24px",
        md: "16px",
        lg: "24px",
        base: "4px",
        "2xl": "64px",
      },
      fontFamily: {
        display: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
        "headline-lg": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
        "label-sm": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
        "label-md": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
        "body-lg": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
        "headline-md": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
        "body-md": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
      },
      animation: {
        "pulse-sage": "pulse-sage 2s infinite ease-in-out",
        "entrance": "fade-in-up 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "scan": "scan 4s linear infinite",
        "shimmer": "shimmer 2s infinite",
        "count-up": "count-up 1.5s ease-out forwards",
      },
      keyframes: {
        "pulse-sage": {
          "0%": { transform: "scale(0.95)", opacity: "0.8" },
          "50%": { transform: "scale(1.1)", opacity: "1" },
          "100%": { transform: "scale(0.95)", opacity: "0.8" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scan": {
          "from": { top: "0" },
          "to": { top: "100%" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
      },
    },
  },
  plugins: [],
};
